name: installment_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dio: ^5.4.0
  provider: ^6.1.2
  shared_preferences: ^2.2.3

  # ✅ เพิ่ม dependencies ใหม่ที่นี่ (เพิ่มลงไปใต้บรรทัดนี้เลย)
  image_picker: ^1.1.1
  geolocator: ^12.0.0
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
